AllCops:
  NewCops: disable
  Exclude:
    - 'bin/**/*'
    - 'doc/**/*'
    - 'examples/**/*'
    - 'log/**/*'
    - 'test/**/*'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Gemspec/OrderedDependencies:
  Exclude:
    - 'rails_com.gemspec'

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'rails_com.gemspec'

# Offense count: 1
# Configuration parameters: IgnoreImplicitReferences.
Lint/ShadowedArgument:
  Exclude:
    - 'lib/rails_com/action_controller/public_exceptions.rb'

# Offense count: 1
# Configuration parameters: AllowComments.
Lint/SuppressedException:
  Exclude:
    - 'lib/rails_com/all.rb'

# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'lib/rails_com/active_storage/attached_macros.rb'

# Offense count: 25
# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 51

# Offense count: 2
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 66

# Offense count: 7
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 16

# Offense count: 33
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods.
Metrics/MethodLength:
  Max: 27

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

# Offense count: 5
# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 17

# Offense count: 1
# Configuration parameters: NamePrefix, ForbiddenPrefixes, AllowedMethods, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# ForbiddenPrefixes: is_, has_, have_
# AllowedMethods: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Exclude:
    - 'lib/rails_com/active_record/translation.rb'

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 106
Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

# Offense count: 104
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false


# Offense count: 13
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, Autocorrect.
# SupportedStyles: module_function, extend_self, forbidden
Style/ModuleFunction:
  Exclude:
    - 'lib/rails_com/meta/controllers.rb'
    - 'lib/rails_com/meta/env.rb'
    - 'lib/rails_com/meta/models.rb'
    - 'lib/rails_com/meta/routes.rb'
    - 'lib/rails_com/utils/babel.rb'
    - 'lib/rails_com/utils/deploy.rb'
    - 'lib/rails_com/utils/hex_helper.rb'
    - 'lib/rails_com/utils/ip_helper.rb'
    - 'lib/rails_com/utils/jobber.rb'
    - 'lib/rails_com/utils/num_helper.rb'
    - 'lib/rails_com/utils/qrcode_helper.rb'
    - 'lib/rails_com/utils/time_helper.rb'
    - 'lib/rails_com/utils/uid_helper.rb'

# Offense count: 17
# Cop supports --auto-correct.
Style/MultilineIfModifier:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'lib/rails_com/utils/qrcode_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Strict.
Style/NumericLiterals:
  MinDigits: 6

# Offense count: 6
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle, IgnoredMethods.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'app/helpers/rails_com/active_helper.rb'
    - 'app/helpers/rails_com/time_helper.rb'
    - 'lib/rails_com/utils/time_helper.rb'

# Offense count: 7
Style/OptionalArguments:
  Exclude:
    - 'lib/rails_com/core/hash.rb'
    - 'lib/rails_com/utils/time_helper.rb'
    - 'lib/rails_com/webpacker/yaml_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'lib/rails_com/action_controller/parameters.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantCondition:
  Exclude:
    - 'app/controllers/rails_com/application.rb'
    - 'lib/rails_com/active_record/enum.rb'

# Offense count: 11
# Cop supports --auto-correct.
Style/RedundantInterpolation:
  Exclude:
    - 'examples/config/puma.rb'
    - 'examples/config/puma/development.rb'
    - 'examples/config/puma/production.rb'
    - 'examples/config/puma/staging.rb'

# Offense count: 2
# Cop supports --auto-correct.
Style/RedundantParentheses:
  Exclude:
    - 'lib/rails_com/utils/num_helper.rb'

# Offense count: 41
# Cop supports --auto-correct.
Style/RedundantSelf:
  Exclude:
    - 'app/controllers/rails_com/application.rb'
    - 'app/models/rails_com/acme_account.rb'
    - 'app/models/rails_com/acme_order.rb'
    - 'app/models/rails_com/state_machine.rb'
    - 'lib/rails_com/action_controller/extend.rb'
    - 'lib/rails_com/action_controller/include.rb'
    - 'lib/rails_com/active_record/extend.rb'
    - 'lib/rails_com/active_record/include.rb'
    - 'lib/rails_com/active_record/translation.rb'
    - 'lib/rails_com/active_storage/activestorage_attached.rb'
    - 'lib/rails_com/active_storage/attachment_transfer.rb'
    - 'lib/rails_com/active_storage/blob_prepend.rb'
    - 'lib/rails_com/active_storage/video_response.rb'
    - 'lib/rails_com/core/array.rb'
    - 'lib/rails_com/core/hash.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'app/channels/rails_com/connection.rb'
    - 'lib/rails_com/meta/models.rb'

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: ConvertCodeThatCanStartToReturnNil, AllowedMethods.
# AllowedMethods: present?, blank?, presence, try, try!
Style/SafeNavigation:
  Exclude:
    - 'app/models/rails_com/acme_order.rb'
    - 'lib/rails_com/action_view/template_renderer.rb'
    - 'lib/rails_com/active_record/i18n.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/SelfAssignment:
  Exclude:
    - 'lib/rails_com/utils/uid_helper.rb'

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: AllowAsExpressionSeparator.
Style/Semicolon:
  Exclude:
    - 'config/locales/zh.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: .
# SupportedStyles: use_perl_names, use_english_names
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: require_parentheses, require_no_parentheses
Style/StabbyLambdaParentheses:
  Exclude:
    - 'lib/rails_com/engine.rb'

# Offense count: 139
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'app/helpers/rails_com/format_helper.rb'
    - 'config/locales/zh.rb'
    - 'lib/rails_com/utils/deploy.rb'
    - 'test/factories/active_storage_attachments.rb'
    - 'test/factories/active_storage_blobs.rb'
    - 'test/factories/cache_lists.rb'
    - 'test/system/com/panel/acme_accounts_test.rb'
    - 'test/system/com/panel/acme_authorizations_test.rb'
    - 'test/system/com/panel/acme_identifiers_test.rb'
    - 'test/system/com/panel/acme_orders_test.rb'
    - 'test/system/com/panel/inbound_emails_test.rb'

# Offense count: 26
# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Offense count: 4
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
# IgnoredMethods: respond_to, define_method
Style/SymbolProc:
  Exclude:
    - 'lib/generators/rails_com/migrations_generator.rb'
    - 'lib/rails_com/action_controller/extend.rb'
    - 'lib/rails_com/active_record/extend.rb'
    - 'lib/rails_com/generators/migration_attributes.rb'

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInArrayLiteral:
  Exclude:
    - 'lib/rails_com/all.rb'

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowNamedUnderscoreVariables.
Style/TrailingUnderscoreVariable:
  Exclude:
    - 'app/helpers/rails_com/assets_helper.rb'

# Offense count: 3
# Cop supports --auto-correct.
Style/WhenThen:
  Exclude:
    - 'config/locales/zh.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/WhileUntilDo:
  Exclude:
    - 'examples/qiniu_helper.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: MinSize, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: brackets

# Offense count: 2
# Cop supports --auto-correct.
Style/ZeroLengthPredicate:
  Exclude:
    - 'app/helpers/rails_com/active_helper.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 162
