AllCops:
  NewCops: disable
  Exclude:
    - 'bin/**/*'
    - 'doc/**/*'
    - 'examples/**/*'
    - 'log/**/*'
    - 'test/**/*'

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Gemspec/OrderedDependencies:
  Exclude:
    - 'rails_com.gemspec'

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'rails_com.gemspec'

# Offense count: 1
# Configuration parameters: IgnoreImplicitReferences.
Lint/ShadowedArgument:
  Exclude:
    - 'lib/rails_com/action_controller/public_exceptions.rb'

# Offense count: 1
# Configuration parameters: AllowComments.
Lint/SuppressedException:
  Exclude:
    - 'lib/rails_com/all.rb'

# Offense count: 1
Lint/UselessAssignment:
  Exclude:
    - 'lib/rails_com/active_storage/attached_macros.rb'

# Offense count: 25
# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 51

# Offense count: 2
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 66

# Offense count: 7
# Configuration parameters: IgnoredMethods.
Metrics/CyclomaticComplexity:
  Max: 16

# Offense count: 33
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods.
Metrics/MethodLength:
  Max: 27

# Offense count: 1
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 6

# Offense count: 5
# Configuration parameters: IgnoredMethods.
Metrics/PerceivedComplexity:
  Max: 17

# Offense count: 1
# Configuration parameters: NamePrefix, ForbiddenPrefixes, AllowedMethods, MethodDefinitionMacros.
# NamePrefix: is_, has_, have_
# ForbiddenPrefixes: is_, has_, have_
# AllowedMethods: is_a?
# MethodDefinitionMacros: define_method, define_singleton_method
Naming/PredicateName:
  Exclude:
    - 'lib/rails_com/active_record/translation.rb'

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Offense count: 106
Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

# Offense count: 104
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

# Offense count: 7
Style/OptionalArguments:
  Exclude:
    - 'lib/rails_com/core/hash.rb'
    - 'lib/rails_com/utils/time_helper.rb'
    - 'lib/rails_com/webpacker/yaml_helper.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/SelfAssignment:
  Exclude:
    - 'lib/rails_com/utils/uid_helper.rb'

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

# Offense count: 26
# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Offense count: 3
# Cop supports --auto-correct.
Style/WhenThen:
  Exclude:
    - 'config/locales/zh.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/WhileUntilDo:
  Exclude:
    - 'examples/qiniu_helper.rb'

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: MinSize, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: brackets

# Offense count: 2
# Cop supports --auto-correct.
Style/ZeroLengthPredicate:
  Exclude:
    - 'app/helpers/rails_com/active_helper.rb'

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 162
