default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: true
  additional_paths: []
  engine_paths: []
  cache_manifest: false
development:
  <<: *default
  compile: true
  public_output_path: packs-dev
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    pretty: true
    headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Headers: x-csrf-token, x-requested-with
    watch_options:
      ignored: '**/node_modules/**'
test:
  <<: *default
  compile: true
  public_output_path: packs-test
staging:
  <<: *default
  compile: false
  cache_manifest: true
production:
  <<: *default
  compile: false
  cache_manifest: true
