default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false
  additional_paths:
  - app/javascript/stylesheets
  cache_manifest: false
  extract_css: true
  ignore: '**/_*.scss'
development:
  <<: *default
  public_output_path: packs_dev
  compile: true
  check_yarn_integrity: true
  dev_server:
    https: false
    host: localhost
    port: 3100
    public: localhost:3100
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Headers: x-csrf-token, x-requested-with
    watch_options:
      ignored: '**/node_modules/**'
test:
  <<: *default
  compile: true
  public_output_path: packs-test
  cache_manifest: true
staging:
  <<: *default
  compile: false
  cache_manifest: true
production:
  <<: *default
  compile: false
  cache_manifest: true
