default: &default
  additional_paths: []
  engine_paths: [app/views]
development:
  <<: *default
  public_output_path: packs-dev
  dev_server:
    disableHostCheck: true
    headers:
      Access-Control-Allow-Headers: x-csrf-token, x-requested-with
test:
  <<: *default
  public_output_path: packs-test
staging:
  <<: *default
  compile: false
  cache_manifest: true
production:
  <<: *default
  compile: false
